// ─────────────────────────────────────────────────────────────
//  DESTINATIONS DATABASE — Max Dinamyte Travel
//  This file is auto-managed by the admin panel (admin-destinations.html)
//  You can also edit it directly if you prefer.
// ─────────────────────────────────────────────────────────────

const DESTINATIONS = [

  // ══ EUROPE ══════════════════════════════════════════════════

  { name:"Lisbon", country:"Portugal", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:7, driveFromUS:false, description:"One of Europe's most walkable and affordable capitals, with hilltop viewpoints, vintage trams, and incredible seafood. The locals are famously welcoming and the nightlife runs late without feeling intimidating.", tags:["Walkable","Great food","Historic","Affordable","Nightlife"] },

  { name:"Porto", country:"Portugal", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:7, driveFromUS:false, description:"Porto is Lisbon's smaller, grittier sibling — a UNESCO-listed city of azulejo tiles, port wine cellars, and stunning riverside views. Compact enough to explore on foot and far less crowded than Lisbon.", tags:["Wine","UNESCO","Riverside","Compact","Charming"] },

  { name:"Alentejo", country:"Portugal", advisoryLevel:1, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:7, driveFromUS:false, description:"Portugal's vast interior plateau of rolling cork forests, medieval walled villages, and some of the country's finest wines. Almost no tourists, extraordinary food, and a pace of life that feels like another century.", tags:["Wine","Rural","Peaceful","Medieval","Authentic"] },

  { name:"Barcelona", country:"Spain", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:8, driveFromUS:false, description:"Europe's ultimate party city — clubs don't get going until 2am, beaches buzz all summer, and Gaudí's architecture makes daytime equally spectacular. Built for groups who want to split up and reunite over long late dinners.", tags:["Nightlife","Beach","Architecture","Food & drink","Groups"] },

  { name:"San Sebastián", country:"Spain", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:8, driveFromUS:false, description:"San Sebastián has more Michelin stars per capita than almost anywhere on earth — the pintxos bars alone are worth the trip. Nestled between mountains and a perfect crescent beach, it's one of Europe's most beautiful small cities.", tags:["Foodie paradise","Beach","Michelin stars","Scenic","Relaxed"] },

  { name:"Seville", country:"Spain", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:8, driveFromUS:false, description:"Seville is Andalusia at its most dramatic — flamenco, grand cathedrals, orange-tree-lined plazas, and a tapas culture that keeps restaurants buzzing until midnight. Couples and groups alike get swept up in its passion.", tags:["Flamenco","History","Tapas","Romantic","Architecture"] },

  { name:"Ibiza Town", country:"Spain", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:false, goodForFamilies:false, goodForYoungKids:false, flightHours:9, driveFromUS:false, description:"The world's most famous party island — legendary clubs, world-class DJs, and a summer season that runs June through October. Beyond the clubs, the old walled town is a UNESCO site with great restaurants.", tags:["Clubbing","Beach","DJ culture","Summer","Legendary"] },

  { name:"Granada", country:"Spain", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:8, driveFromUS:false, description:"Granada is home to the Alhambra, one of the world's great palaces, set dramatically against the Sierra Nevada. Tapas are still free with every drink here, and the Moorish old quarter is one of Spain's most magical neighborhoods.", tags:["Alhambra","Free tapas","Moorish","History","Affordable"] },

  { name:"Mallorca", country:"Spain", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Beyond the package-holiday resorts, Mallorca hides a stunning mountainous interior, hidden coves only accessible by boat, and beautiful stone villages. It's an island that thoroughly rewards travelers willing to rent a car and explore.", tags:["Hidden coves","Mountains","Beaches","Scenic","Diverse"] },

  { name:"Rome", country:"Italy", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Rome is an open-air museum where you can eat the world's best cacio e pepe fifty meters from a 2,000-year-old monument. Every neighborhood has its own character, perfect for groups who want to explore independently and regroup over dinner.", tags:["History","Food","Art","Walking","Iconic"] },

  { name:"Amalfi Coast", country:"Italy", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:false, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:9, driveFromUS:false, description:"Cliffside villages tumbling into a turquoise sea, fresh pasta, and limoncello at sunset — the definitive romantic Italian escape. It rewards slow travel: hire a boat, eat too much, do nothing.", tags:["Romantic","Coastal","Scenic","Italian food","Slow travel"] },

  { name:"Florence", country:"Italy", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Florence is the world's greatest concentration of Renaissance art in a compact, walkable city — the Uffizi, Michelangelo's David, and Brunelleschi's dome, all within walking distance of extraordinary food and wine.", tags:["Art","Renaissance","Walkable","Food","Wine"] },

  { name:"Venice", country:"Italy", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:9, driveFromUS:false, description:"Venice is genuinely like nowhere else on earth — a city built on water where getting lost in the maze of canals is the whole point. Go in shoulder season (April or October) to avoid the worst crowds.", tags:["Unique","Canals","Romantic","Art","Architecture"] },

  { name:"Sicily", country:"Italy", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:10, driveFromUS:false, description:"Sicily is Italy turned up to eleven — more ancient Greek ruins, more dramatic coastline, more extraordinary food, and half the tourists of the mainland. A destination that rewards curiosity and repays every traveler who ventures beyond the obvious.", tags:["Ancient ruins","Food","Beaches","Authentic","Underrated"] },

  { name:"Bologna", country:"Italy", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:9, driveFromUS:false, description:"Italy's most underrated city is also its greatest food city — birthplace of ragù, mortadella, and tortellini, with a lively university town energy and almost no tourist crowds. Italians go to Bologna to eat.", tags:["Food capital","University town","Authentic","Local","Underrated"] },

  { name:"Cinque Terre", country:"Italy", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:9, driveFromUS:false, description:"Five colorful fishing villages clinging to dramatic cliffs above the Ligurian Sea, connected by coastal hiking trails and a train. Best in May or September when the crowds thin and the light turns golden.", tags:["Scenic","Hiking","Coastal","Colorful","Villages"] },

  { name:"Dubrovnik", country:"Croatia", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:10, driveFromUS:false, description:"The walled old city rising above the Adriatic is one of the most jaw-dropping sights in Europe. Walk the city walls at sunset, island-hop by boat, and eat seafood at harbor-side restaurants.", tags:["Walled city","Adriatic","Island hopping","Scenic","Historic"] },

  { name:"Hvar Island", country:"Croatia", advisoryLevel:1, vibe:"nightlife", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:10, driveFromUS:false, description:"Croatia's party island — a glamorous mix of yacht-filled harbors, cliff bars, and some of the best open-air clubs in Europe. By day it's lavender fields and hidden coves; by night it's one long party.", tags:["Nightlife","Yacht scene","Island","Beach","Glamorous"] },

  { name:"Split", country:"Croatia", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:10, driveFromUS:false, description:"Split is built literally inside a 1,700-year-old Roman emperor's palace — people live, eat, and party inside ancient walls. It's Croatia's most authentic city and the perfect base for exploring the Dalmatian islands.", tags:["Roman palace","Authentic","Coastal","Historic","Active"] },

  { name:"Amsterdam", country:"Netherlands", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:8, driveFromUS:false, description:"Amsterdam's canal-ringed streets, world-class museums, and legendary café culture make it one of Europe's most liveable cities. Endlessly explorable by bike, with a food and bar scene that rewards groups willing to wander.", tags:["Canals","Museums","Cycling","Nightlife","Culture"] },

  { name:"Copenhagen", country:"Denmark", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:8, driveFromUS:false, description:"Copenhagen consistently ranks among the world's most liveable cities. The food scene is extraordinary (home of Noma), the design culture is inspiring, and the waterfront Nyhavn district is one of Europe's most photogenic.", tags:["Design","Food scene","Waterfront","Cycling","Hygge"] },

  { name:"Reykjavik", country:"Iceland", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:5, driveFromUS:false, description:"Iceland's tiny capital is the gateway to some of the world's most dramatic landscapes — northern lights, geysers, waterfalls, and black sand beaches all within a few hours' drive. The city itself is quirky, walkable, and surprisingly lively.", tags:["Northern lights","Nature","Geysers","Unique","Adventure"] },

  { name:"Prague", country:"Czech Republic", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Prague's fairy-tale old town — cobblestone streets, medieval bridges, and a hilltop castle — is one of Europe's best-preserved historic city centers. Far more affordable than Western Europe with outstanding food, beer, and culture.", tags:["Historic","Affordable","Beautiful","Beer culture","Walkable"] },

  { name:"Ljubljana", country:"Slovenia", advisoryLevel:1, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Slovenia's tiny capital is one of Europe's best-kept secrets — a car-free old town draped along a river, a hilltop castle, and the stunning Lake Bled just 45 minutes away. Peaceful, incredibly beautiful, and almost tourist-free.", tags:["Hidden gem","Car-free","Castle","Lake Bled nearby","Peaceful"] },

  { name:"Lake Bled", country:"Slovenia", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"A glacial lake with a fairy-tale island church and a clifftop castle — Lake Bled looks almost too beautiful to be real. It's an easy day trip from Ljubljana or a perfect overnight destination in its own right.", tags:["Fairy-tale","Lake","Castle","Scenic","Peaceful"] },

  { name:"Athens", country:"Greece", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:10, driveFromUS:false, description:"Athens wears its 3,000 years lightly — the Acropolis rises above a buzzing modern city with a great food scene, nightlife, and some of the most welcoming people in Europe. More affordable than most European capitals.", tags:["Acropolis","History","Food","Nightlife","Affordable"] },

  { name:"Santorini", country:"Greece", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:false, goodForGroups:false, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:10, driveFromUS:false, description:"The whitewashed villages and blue-domed churches perched above the caldera are as spectacular in person as they look in photographs. Go for the sunsets, the local wines, and the extraordinary volcanic beaches.", tags:["Romantic","Sunsets","Iconic","Wine","Caldera views"] },

  { name:"Mykonos", country:"Greece", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:10, driveFromUS:false, description:"Mykonos is Greece's party island — beach clubs, world-famous DJs, a glamorous international crowd, and a charming whitewashed windmill town to explore when you eventually surface. Best June through September.", tags:["Beach clubs","Nightlife","Glamorous","DJ scene","Summer"] },

  { name:"Thessaloniki", country:"Greece", advisoryLevel:1, vibe:"culture", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:10, driveFromUS:false, description:"Greece's second city is its most underrated — a lively waterfront city with Byzantine churches, a buzzing food market, and a meze culture that puts Athens to shame. Almost no tourists despite being genuinely extraordinary.", tags:["Food market","Byzantine","Waterfront","Authentic","Underrated"] },

  { name:"Tallinn", country:"Estonia", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Tallinn's medieval old town is one of the best-preserved in Europe — cobblestone streets, ancient towers, and ramparts surrounding a beautifully walkable city center. Incredibly affordable and utterly charming.", tags:["Medieval","Affordable","Walkable","Charming","UNESCO"] },

  { name:"Vienna", country:"Austria", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Vienna is Europe's grandest imperial city — extraordinary museums, coffee house culture, opera, and some of the world's finest pastry. It's elegant without being stuffy, and surprisingly accessible for families.", tags:["Imperial","Coffee culture","Museums","Opera","Elegant"] },

  { name:"Salzburg", country:"Austria", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Mozart's birthplace sits at the foot of the Alps in a picture-perfect Baroque city — a UNESCO-listed old town, mountain cable cars, and the most scenic surroundings of any city in Central Europe.", tags:["Baroque","Alps","Mozart","UNESCO","Scenic"] },

  { name:"Edinburgh", country:"United Kingdom", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:7, driveFromUS:false, description:"Edinburgh is one of the world's great capital cities — a dramatic castle on a volcanic rock, a medieval Old Town, a Georgian New Town, and some of the world's best whisky bars. In August, the Fringe festival turns it into something else entirely.", tags:["Castle","Whisky","History","Fringe festival","Dramatic"] },

  { name:"Dublin", country:"Ireland", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:7, driveFromUS:false, description:"Dublin's pub culture is the stuff of legend — live traditional music, extraordinary conversation, and a warmth that makes strangers feel like old friends within minutes. The city is compact, walkable, and endlessly entertaining.", tags:["Pubs","Live music","Craic","Walkable","Friendly"] },

  { name:"Galway", country:"Ireland", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:7, driveFromUS:false, description:"Ireland's most characterful city is a gateway to the wild Atlantic Way — a bohemian, music-filled town with a brilliant food scene and the dramatic Connemara landscape on its doorstep. Far more authentic than Dublin.", tags:["Music","Bohemian","Atlantic","Food","Authentic"] },

  { name:"Bruges", country:"Belgium", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:8, driveFromUS:false, description:"Bruges is a medieval masterpiece — canals, Gothic architecture, chocolate shops, and a pace of life that feels centuries removed from the modern world. The most perfectly preserved medieval city in Europe.", tags:["Medieval","Canals","Chocolate","Beer","Romantic"] },

  { name:"Ghent", country:"Belgium", advisoryLevel:1, vibe:"culture", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:8, driveFromUS:false, description:"Ghent is Belgium's most overlooked city — a spectacular medieval center with three towers, one of Europe's greatest paintings (the Ghent Altarpiece), and a thriving craft beer and restaurant scene with almost no tourists.", tags:["Medieval","Beer","Authentic","Art","Hidden gem"] },

  { name:"Zurich", country:"Switzerland", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Switzerland's largest city sits on a lake with Alps on the horizon — extraordinarily beautiful, impeccably clean, and a gateway to some of the world's best skiing and hiking. Expensive but genuinely exceptional.", tags:["Lake","Alps","Clean","Safe","Stunning"] },

  { name:"Lucerne", country:"Switzerland", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:9, driveFromUS:false, description:"Lucerne's medieval covered bridges, lake setting, and mountain backdrop make it one of Central Europe's most scenic towns. Take the cogwheel railway up Mount Rigi or Mount Pilatus for views that justify the entire trip.", tags:["Scenic","Lake","Mountains","Medieval","Peaceful"] },

  { name:"Interlaken", country:"Switzerland", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:9, driveFromUS:false, description:"Nestled between two lakes with the Jungfrau massif towering above, Interlaken is the adventure sports capital of the Alps — paragliding, skydiving, canyon jumping, and world-class skiing all in one valley.", tags:["Adventure","Alps","Paragliding","Skiing","Stunning"] },

  // ══ ASIA ════════════════════════════════════════════════════

  { name:"Tokyo", country:"Japan", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:14, driveFromUS:false, description:"Tokyo is the greatest city on earth for food, and arguably for everything else — impossibly safe, endlessly fascinating, and unlike anywhere you've ever been. Solo travelers thrive here; the city rewards wandering in any direction.", tags:["Food paradise","Ultramodern","Safe","Culture","Unique"] },

  { name:"Kyoto", country:"Japan", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:14, driveFromUS:false, description:"Kyoto is Japan's cultural soul — 1,600 Buddhist temples, Shinto shrines, geisha districts, and bamboo forests in a compact, easily navigable city. The perfect antidote to Tokyo's intensity and one of the world's great slow-travel destinations.", tags:["Temples","Zen","Traditional","Bamboo","Peaceful"] },

  { name:"Osaka", country:"Japan", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:14, driveFromUS:false, description:"Osaka is Japan's food capital and its most fun city — street food stalls, a raucous nightlife district (Dotonbori), and a warmth and humor that sets it apart from Tokyo's polish. Locals will insist you eat until you can't move.", tags:["Street food","Nightlife","Fun","Foodie","Lively"] },

  { name:"Hiroshima & Miyajima", country:"Japan", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:14, driveFromUS:false, description:"Hiroshima's Peace Memorial and the iconic floating torii gate on nearby Miyajima Island make this one of Japan's most moving and beautiful destinations. The city itself has rebuilt into a vibrant, modern place with great food.", tags:["Historic","Peaceful","Iconic torii","Moving","Beautiful"] },

  { name:"Bangkok", country:"Thailand", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:17, driveFromUS:false, description:"Bangkok is chaotic, thrilling, and completely addictive — world-class street food, ornate temples, rooftop bars, and a nightlife scene that goes until sunrise. Solo travelers love it for ease of meeting people; groups love the sheer variety.", tags:["Street food","Temples","Nightlife","Buzzing","Affordable"] },

  { name:"Chiang Mai", country:"Thailand", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:18, driveFromUS:false, description:"Chiang Mai is northern Thailand at its most serene — ancient walled temples, jungle-fringed mountains, cooking classes, elephant sanctuaries, and a thriving café culture. Travelers arrive for a week and stay for a month.", tags:["Temples","Jungle","Cooking classes","Peaceful","Affordable"] },

  { name:"Koh Lanta", country:"Thailand", advisoryLevel:1, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:18, driveFromUS:false, description:"Koh Lanta is Thailand's most laid-back island — long sandy beaches, clear water, mangrove forests, and a pace of life that makes other Thai islands feel hectic. No full moon parties; just hammocks, fresh seafood, and sunsets.", tags:["Beach","Laid-back","Snorkeling","Relaxed","Hidden"] },

  { name:"Bali", country:"Indonesia", advisoryLevel:2, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:20, driveFromUS:false, description:"Bali's combination of lush rice terraces, Hindu temples, world-class surf, and an extraordinary wellness scene makes it one of the world's most complete destinations. Ubud for culture and calm; Seminyak and Canggu for nightlife.", tags:["Wellness","Temples","Surf","Rice terraces","Spiritual"] },

  { name:"Singapore", country:"Singapore", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:18, driveFromUS:false, description:"Singapore is Asia's most polished city — impossibly clean, extraordinarily safe, and home to one of the world's greatest food scenes from hawker stalls to Michelin-starred restaurants. Its futuristic gardens and architecture are unlike anything else.", tags:["Safe","Food","Futuristic","Clean","Family-friendly"] },

  { name:"Penang", country:"Malaysia", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:19, driveFromUS:false, description:"Penang is Southeast Asia's food capital — a UNESCO-listed island where Chinese, Malay, and Indian cultures have created one of the world's most extraordinary street food scenes. George Town's street art and heritage shophouses are equally spectacular.", tags:["Food capital","Street art","UNESCO","Multicultural","Affordable"] },

  { name:"Luang Prabang", country:"Laos", advisoryLevel:2, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:20, driveFromUS:false, description:"One of Southeast Asia's most magical towns — a UNESCO-listed peninsula where Buddhist monks collect alms at dawn, waterfalls cascade through jungle, and the Mekong flows past French colonial villas. Almost no one goes here, and those who do never forget it.", tags:["UNESCO","Monks","Jungle","Mekong","Untouched"] },

  { name:"Seoul", country:"South Korea", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:14, driveFromUS:false, description:"Seoul is Asia's most exciting city right now — K-pop culture, extraordinary food, 24-hour neighborhoods, and a nightlife scene centered on Itaewon and Hongdae that never really stops. Incredibly safe, efficient, and addictively fun.", tags:["K-pop","Nightlife","Food","24-hour city","Exciting"] },

  { name:"Taipei", country:"Taiwan", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:15, driveFromUS:false, description:"Taiwan's capital is criminally underrated — extraordinary night markets, the world's best bubble tea, stunning mountain day trips, and some of the friendliest people in Asia. It's also one of the safest and most LGBTQ+-friendly cities in the region.", tags:["Night markets","Food","Friendly","Safe","Underrated"] },

  { name:"Hoi An", country:"Vietnam", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:19, driveFromUS:false, description:"Hoi An's ancient trading port — lantern-lit streets, centuries-old merchant houses, and the most beautiful tailors in the world — is one of Southeast Asia's most atmospheric towns. The beach is 10 minutes away; the food is extraordinary.", tags:["Lanterns","Ancient town","Tailors","Beach nearby","Atmospheric"] },

  { name:"Ha Long Bay", country:"Vietnam", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:19, driveFromUS:false, description:"Thousands of limestone karst islands rising from emerald water — Ha Long Bay is one of the world's great natural wonders. Explore by overnight cruise ship, kayak into hidden caves, and watch the mist roll across the bay at dawn.", tags:["Natural wonder","Cruise","Kayaking","Limestone karsts","Stunning"] },

  { name:"Maldives", country:"Maldives", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:false, goodForGroups:false, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:17, driveFromUS:false, description:"The Maldives is the world's ultimate luxury escape — overwater bungalows, perfectly clear lagoons, and an isolation from the world that makes it the definitive honeymoon destination. There is genuinely nothing to do but be blissfully content.", tags:["Luxury","Overwater villas","Snorkeling","Honeymoon","Pristine"] },

  { name:"Sri Lanka", country:"Sri Lanka", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:17, driveFromUS:false, description:"Sri Lanka packs an extraordinary amount into a small island — ancient ruins, tea-covered hill country, elephant safaris, colonial-era trains, and some of the world's best surf beaches. One of Asia's most underrated destinations.", tags:["Tea country","Elephants","Ancient ruins","Surf","Underrated"] },

  // ══ MIDDLE EAST ═════════════════════════════════════════════

  { name:"Dubai", country:"United Arab Emirates", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:13, driveFromUS:false, description:"Dubai is the world's most audacious city — the tallest building, the largest mall, indoor skiing in the desert, and a nightlife scene that caters to every taste. Also one of the safest cities on earth, making it excellent for solo travelers.", tags:["Luxury","Nightlife","Ultramodern","Safe","Unique"] },

  { name:"Abu Dhabi", country:"United Arab Emirates", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:13, driveFromUS:false, description:"Abu Dhabi is Dubai's more refined, less frantic neighbor — home to the jaw-dropping Sheikh Zayed Grand Mosque, the Louvre Abu Dhabi, and Formula 1's Yas Marina Circuit. Quieter, more cultural, and equally safe.", tags:["Grand Mosque","Louvre","Culture","Refined","Safe"] },

  { name:"Amman", country:"Jordan", advisoryLevel:2, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:11, driveFromUS:false, description:"Amman is a surprisingly hip, welcoming capital with great coffee shops, a booming food scene, and easy access to Petra and the Dead Sea. Jordan is one of the safest countries in the Middle East with some of the world's most hospitable people.", tags:["Petra nearby","Dead Sea","Hospitable","History","Food scene"] },

  { name:"Petra", country:"Jordan", advisoryLevel:2, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:11, driveFromUS:false, description:"The rose-red ancient Nabataean city carved into sheer rock is one of the world's true wonders — and it's even more spectacular than the photographs suggest. Enter through the narrow Siq canyon at dawn before the crowds arrive.", tags:["Wonder of the world","Ancient","Spectacular","Historic","Bucket list"] },

  { name:"Muscat", country:"Oman", advisoryLevel:1, vibe:"culture", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:14, driveFromUS:false, description:"Oman's capital is the Middle East's most pleasant surprise — a spotlessly clean, strikingly beautiful city of white mosques, souks, and mountain scenery, with the warmest, most genuinely welcoming people of any country in the region.", tags:["Hidden gem","Welcoming","Clean","Souks","Mountains"] },

  { name:"Wahiba Sands", country:"Oman", advisoryLevel:1, vibe:"calm", familiarity:"hidden", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:14, driveFromUS:false, description:"Oman's great desert, stretching 180km south of Muscat, is one of the world's most accessible yet genuinely remote desert experiences — camel rides, dune camping under staggering stars, and a silence that resets everything.", tags:["Desert","Stars","Camels","Remote","Unique"] },

  // ══ AFRICA ══════════════════════════════════════════════════

  { name:"Marrakech", country:"Morocco", advisoryLevel:2, vibe:"culture", familiarity:"famous", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:8, driveFromUS:false, description:"Marrakech's medina is one of the world's great sensory experiences — labyrinthine souks, rooftop riads, the chaotic magic of Djemaa el-Fna, and extraordinary food. Best experienced with a companion or group.", tags:["Medina","Souks","Riads","Vibrant","Exotic"] },

  { name:"Fes", country:"Morocco", advisoryLevel:2, vibe:"culture", familiarity:"offbeat", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:8, driveFromUS:false, description:"Fes el-Bali is the world's largest car-free urban area — a medieval medina of thousands of alleyways, ancient madrasas, leather tanneries, and a way of life virtually unchanged for centuries. More authentic and less touristy than Marrakech.", tags:["Medieval medina","Tanneries","Authentic","Historic","Labyrinthine"] },

  { name:"Cape Town", country:"South Africa", advisoryLevel:2, vibe:"culture", familiarity:"famous", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:15, driveFromUS:false, description:"Cape Town is Africa's most spectacular city — Table Mountain, world-class wine, pristine beaches, and a restaurant scene that punches well above its weight. Exercise normal urban caution; best explored with others rather than solo.", tags:["Table Mountain","Wine","Beaches","Stunning scenery","Food"] },

  { name:"Nairobi", country:"Kenya", advisoryLevel:2, vibe:"culture", familiarity:"offbeat", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:15, driveFromUS:false, description:"Nairobi is the gateway to East Africa's extraordinary wildlife — the Maasai Mara is hours away — and a city with a thriving food and arts scene. Go with a group or partner and book reputable tour operators for safaris.", tags:["Safari gateway","Wildlife","Culture","Food scene","Adventure"] },

  { name:"Zanzibar", country:"Tanzania", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:16, driveFromUS:false, description:"Zanzibar's spice-scented Stone Town and impossibly white beaches with turquoise water make it one of Africa's most intoxicating islands. The combination of Swahili culture, Arab architecture, and Indian Ocean beauty is utterly unique.", tags:["White beaches","Stone Town","Spice island","Snorkeling","Unique"] },

  { name:"Kigali", country:"Rwanda", advisoryLevel:1, vibe:"culture", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:16, driveFromUS:false, description:"Rwanda's capital is Africa's cleanest, safest, most orderly city — and the gateway to gorilla trekking in Volcanoes National Park, one of the world's great wildlife experiences. The country's transformation story is as inspiring as its landscapes.", tags:["Gorilla trekking","Safe","Clean","Africa","Inspiring"] },

  { name:"Mauritius", country:"Mauritius", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:false, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:17, driveFromUS:false, description:"Mauritius is the Indian Ocean's most complete island — white sand beaches, a turquoise lagoon, lush mountains, and a multicultural cuisine that fuses Indian, Chinese, French, and Creole influences. The most underrated luxury island destination on earth.", tags:["Beach","Lagoon","Luxury","Multicultural food","Romantic"] },

  // ══ LATIN AMERICA ═══════════════════════════════════════════

  { name:"Mexico City", country:"Mexico", advisoryLevel:2, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:4, driveFromUS:false, description:"One of the world's great capitals — a 3,000-year-old city with world-class museums, the best food scene in the Americas, incredible neighborhoods, and a nightlife that runs until dawn. Stick to Condesa, Roma, and Polanco for a safe, thrilling experience.", tags:["Food","Museums","Nightlife","Culture","Neighborhoods"] },

  { name:"Oaxaca", country:"Mexico", advisoryLevel:2, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:5, driveFromUS:false, description:"Mexico's culinary and indigenous cultural heartland — mole, mezcal, Zapotec ruins, and one of the most vibrant arts scenes in Latin America. Compact, walkable, and has a warm energy that makes solo travelers feel immediately at home.", tags:["Food","Mezcal","Indigenous culture","Arts","Walkable"] },

  { name:"San Miguel de Allende", country:"Mexico", advisoryLevel:2, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:4, driveFromUS:false, description:"A perfectly preserved colonial city in the Mexican highlands, with pink stone churches, cobblestone streets, a thriving expat arts community, and one of the best year-round climates on earth. The most beautiful small city in Mexico.", tags:["Colonial","Arts","Beautiful","Expat community","Year-round sunshine"] },

  { name:"Cartagena", country:"Colombia", advisoryLevel:2, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:4, driveFromUS:false, description:"Cartagena's walled colonial city — bougainvillea-draped balconies, cobblestone streets, and Caribbean color — is one of the most photogenic places in the Americas. The beaches and islands nearby are extraordinary.", tags:["Colonial","Caribbean","Colorful","Beaches","Romantic"] },

  { name:"Medellín", country:"Colombia", advisoryLevel:2, vibe:"nightlife", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:4, driveFromUS:false, description:"Medellín's transformation from the world's most dangerous city to one of Latin America's most innovative is one of travel's great stories. The nightlife in El Poblado is legendary, the spring-like climate is year-round, and the energy is electric.", tags:["Nightlife","Spring climate","Innovation","Energy","Affordable"] },

  { name:"Buenos Aires", country:"Argentina", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:11, driveFromUS:false, description:"The Paris of South America — grand boulevards, world-class steak, tango, and a nightlife culture where dinner doesn't start until 10pm and clubs run until noon the next day. A city that grabs you and doesn't let go.", tags:["Tango","Steak","Nightlife","European feel","Culture"] },

  { name:"Mendoza", country:"Argentina", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:12, driveFromUS:false, description:"Argentina's wine country — Malbec vineyards in the shadow of the Andes, outstanding restaurants, spa hotels, and mountain scenery that rivals anything in Europe. One of the world's great wine destinations at a fraction of Napa or Burgundy prices.", tags:["Wine","Malbec","Andes","Vineyards","Affordable"] },

  { name:"Lima", country:"Peru", advisoryLevel:2, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:7, driveFromUS:false, description:"Latin America's food capital — home to some of the world's best restaurants and a ceviche culture that will ruin all other fish dishes for life. The Miraflores and Barranco neighborhoods are safe, lively, and beautiful.", tags:["Food capital","Ceviche","Machu Picchu nearby","Culture","Coastal"] },

  { name:"Cusco & Sacred Valley", country:"Peru", advisoryLevel:2, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:8, driveFromUS:false, description:"The former Inca capital sits at 11,000 feet, surrounded by ancient ruins and framed by the Andes — it's the gateway to Machu Picchu, one of the world's great wonders. Allow a day to acclimatize and the experience is extraordinary.", tags:["Machu Picchu","Inca","Andes","Ancient","Bucket list"] },

  { name:"Montevideo", country:"Uruguay", advisoryLevel:1, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:11, driveFromUS:false, description:"Uruguay's compact capital is South America's most liveable city — a beautiful waterfront promenade, excellent food and wine, a thriving arts scene, and the safest, most politically stable country on the continent. Completely overlooked by most travelers.", tags:["Underrated","Safe","Waterfront","Food","Quality of life"] },

  { name:"Rio de Janeiro", country:"Brazil", advisoryLevel:2, vibe:"nightlife", familiarity:"famous", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:10, driveFromUS:false, description:"Rio is one of the world's most dramatically beautiful cities — Copacabana, Sugarloaf, the Redeemer, and a samba nightlife culture unlike anything else. Go with others, stay in recommended neighborhoods, and it's an extraordinary experience.", tags:["Carnival","Beaches","Samba","Nightlife","Iconic"] },

  { name:"Patagonia", country:"Chile", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:12, driveFromUS:false, description:"The end of the earth — Torres del Paine's granite towers, glaciers calving into turquoise lakes, and condors riding thermals above a wilderness that makes you feel genuinely small. One of the world's great hiking destinations.", tags:["Hiking","Glaciers","Wilderness","Dramatic","End of the world"] },

  // ══ CARIBBEAN ═══════════════════════════════════════════════

  { name:"San Juan", country:"Puerto Rico", advisoryLevel:2, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:3, driveFromUS:false, description:"Old San Juan's cobblestone streets and colorful colonial buildings are unlike anywhere else in the Caribbean — and as a U.S. territory there are no passport or currency hassles. The beaches, food, and nightlife are all first-rate.", tags:["No passport needed","Colonial","Beach","Food","Easy travel"] },

  { name:"Barbados", country:"Barbados", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:5, driveFromUS:false, description:"Barbados punches above its weight in every category — the most beautiful beaches in the Caribbean, an extraordinary food scene anchored in flying fish and rum, and a warmth of character that makes it stand apart from every other island.", tags:["Beaches","Rum","Friendly","Food","Sophisticated"] },

  { name:"St. Lucia", country:"Saint Lucia", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:false, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:5, driveFromUS:false, description:"St. Lucia's twin volcanic peaks (the Pitons) rising from a jungle-covered island above a turquoise sea make it the Caribbean's most dramatically beautiful island. The best choice for a romantic, nature-focused escape in the region.", tags:["The Pitons","Romantic","Jungle","Snorkeling","Dramatic scenery"] },

  { name:"Providencia Island", country:"Colombia", advisoryLevel:2, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:5, driveFromUS:false, description:"Colombia's secret Caribbean island — tiny, lush, and almost untouched, with some of the clearest water in the Western Hemisphere. No chain hotels, no cruise ships, very few tourists: just reef, jungle, and quiet.", tags:["Remote","Untouched","Snorkeling","Quiet","Hidden gem"] },

  { name:"Trinidad & Tobago", country:"Trinidad and Tobago", advisoryLevel:2, vibe:"culture", familiarity:"hidden", goodForSolo:false, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:5, driveFromUS:false, description:"Trinidad has the Caribbean's greatest food scene (birthplace of doubles, roti, and callaloo) and the world-famous Carnival; Tobago offers pristine reefs and empty beaches. Two islands, two entirely different personalities.", tags:["Carnival","Food","Reef","Authentic","Two islands"] },

  // ══ NORTH AMERICA ═══════════════════════════════════════════

  { name:"New Orleans", country:"United States", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:0, driveFromUS:true, description:"America's most unique city — jazz from every doorway, some of the country's best food, and a party culture on legendary Bourbon Street that never really stops. Built for communal eating, drinking, and dancing.", tags:["Jazz","Food","Nightlife","Unique","Driveable"] },

  { name:"Nashville", country:"United States", advisoryLevel:1, vibe:"nightlife", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:false, goodForYoungKids:false, flightHours:0, driveFromUS:true, description:"Nashville has exploded into one of America's hottest cities — live country music on every corner of Broadway, a rooftop bar scene, and a food culture far more sophisticated than its honky-tonk image suggests. Perfect for groups wanting a long weekend of pure fun.", tags:["Live music","Nightlife","Food","Groups","Driveable"] },

  { name:"Sedona", country:"United States", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:0, driveFromUS:true, description:"Sedona's red rock formations are among the most spectacular landscapes in America, and the town has built a thriving wellness and spa culture around them. Hikers, spiritual seekers, and couples in need of a reset all find what they're looking for.", tags:["Red rocks","Wellness","Hiking","Scenic","Romantic"] },

  { name:"Asheville", country:"United States", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:0, driveFromUS:true, description:"Western North Carolina's mountain gem — a walkable arts district, one of America's best craft beer scenes, incredible farm-to-table restaurants, and the Blue Ridge Parkway on the doorstep. Easy drive from much of the East Coast.", tags:["Craft beer","Arts","Mountains","Food","Driveable"] },

  { name:"Savannah", country:"United States", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:0, driveFromUS:true, description:"Savannah is America's most beautiful city — Spanish moss-draped squares, antebellum mansions, a walkable riverfront, and a relaxed Southern pace that makes every meal feel like an occasion. Perfect for a slow, gentle long weekend.", tags:["Spanish moss","Antebellum","Walkable","Southern food","Romantic"] },

  { name:"Santa Fe", country:"United States", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:0, driveFromUS:true, description:"Santa Fe is America's most culturally distinctive city — 400-year-old adobe buildings, the world's largest Native American art market, extraordinary New Mexican cuisine, and a thriving gallery scene at 7,000 feet elevation.", tags:["Adobe","Native American art","New Mexican food","Galleries","Unique"] },

  { name:"Portland", country:"United States", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:0, driveFromUS:true, description:"Portland is America's most creative city — the best food cart scene in the country, extraordinary craft breweries, a thriving indie music scene, and a Rose City culture that embraces the weird and the wonderful. Oregon wine country is 30 minutes away.", tags:["Food carts","Craft beer","Music","Creative","Pacific Northwest"] },

  { name:"Quebec City", country:"Canada", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:0, driveFromUS:true, description:"The closest thing to Europe without crossing the Atlantic — a UNESCO-listed walled city with French architecture, incredible food, and a culture entirely unlike anywhere else in North America. In winter it becomes a snow globe; in summer a terrace-dining paradise.", tags:["French culture","UNESCO","Walled city","Food","Driveable"] },

  { name:"Vancouver", country:"Canada", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:5, driveFromUS:true, description:"Vancouver sits between mountains and ocean in a way that feels almost too good to be true — world-class skiing, kayaking, hiking, and a food scene driven by an incredible diversity of Asian cuisines. Safe, clean, and endlessly liveable.", tags:["Mountains","Ocean","Outdoors","Food","Safe"] },

  { name:"Banff & Lake Louise", country:"Canada", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:0, driveFromUS:true, description:"The Canadian Rockies at their most spectacular — turquoise glacial lakes, snow-capped peaks, elk wandering through town, and world-class skiing in winter. Banff is the most accessible mountain wilderness destination in North America.", tags:["Rocky Mountains","Turquoise lakes","Wildlife","Skiing","Stunning"] },

  { name:"Prince Edward Island", country:"Canada", advisoryLevel:1, vibe:"calm", familiarity:"hidden", goodForSolo:true, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:0, driveFromUS:true, description:"Canada's smallest province is its most charming — red-sand beaches, lobster fresh off the boat, cycling trails through farmland, and an unhurried pace of life that the rest of the world seems to have forgotten. Perfect for families and couples.", tags:["Lobster","Red sand beaches","Cycling","Peaceful","Family-friendly"] },

  // ══ OCEANIA ═════════════════════════════════════════════════

  { name:"Sydney", country:"Australia", advisoryLevel:1, vibe:"culture", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:20, driveFromUS:false, description:"Sydney's combination of a world-famous harbor, stunning beaches, and a genuinely great food and nightlife scene makes it one of the world's most complete cities. Solo travelers find it easy to meet people; the backpacker and expat communities are huge and welcoming.", tags:["Harbor","Beaches","Nightlife","Safe","English-speaking"] },

  { name:"Melbourne", country:"Australia", advisoryLevel:1, vibe:"culture", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:20, driveFromUS:false, description:"Melbourne consistently wins best city in the world polls, and it's easy to see why — extraordinary coffee culture, a laneway food scene that rivals any city on earth, world-class galleries, and a sports obsession that gives it a unique energy.", tags:["Coffee culture","Laneways","Food","Galleries","Vibrant"] },

  { name:"Great Barrier Reef", country:"Australia", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:21, driveFromUS:false, description:"The world's largest coral reef system — 1,400 miles of extraordinary marine life, diving, and island-hopping from Cairns or the Whitsundays. See it now while climate change still allows; this is a once-in-a-lifetime experience.", tags:["Diving","Snorkeling","Marine life","Natural wonder","Bucket list"] },

  { name:"South Island NZ", country:"New Zealand", advisoryLevel:1, vibe:"calm", familiarity:"offbeat", goodForSolo:true, goodForGroups:true, goodForCouples:true, goodForFamilies:true, goodForYoungKids:false, flightHours:22, driveFromUS:false, description:"Arguably the most scenically dramatic place on earth — fiords, glaciers, mountains, and coastline that look designed by a god showing off. Queenstown is the adventure sports capital of the world; Milford Sound is simply unforgettable.", tags:["Scenery","Adventure","Fiords","Nature","Road trip"] },

  { name:"Fiji", country:"Fiji", advisoryLevel:1, vibe:"calm", familiarity:"famous", goodForSolo:false, goodForGroups:false, goodForCouples:true, goodForFamilies:true, goodForYoungKids:true, flightHours:10, driveFromUS:false, description:"Fiji's 333 islands offer the classic South Pacific experience — overwater bungalows, world-class snorkeling and diving, and the legendary Fijian warmth (the smiles are genuine). The best family and honeymoon destination in the Pacific.", tags:["Overwater bungalows","Snorkeling","Island paradise","Warm","Romantic"] }

];
