const fs = require('fs');

const destinations = [];

// Helper
function d(name,country,al,vibes,fam,solo,groups,couples,fam2,young,fh,drive,direct,desc,tags,extras) {
  const obj = {name,country,advisoryLevel:al,vibes,familiarity:fam,
    goodForSolo:solo,goodForGroups:groups,goodForCouples:couples,
    goodForFamilies:fam2,goodForYoungKids:young,
    flightHours:fh,driveFromUS:drive,directFlight:direct,description:desc,tags};
  if(extras) Object.assign(obj,extras);
  return obj;
}

// EUROPE - IBERIAN
destinations.push(
d("Lisbon","Portugal",1,["culture","nightlife"],"famous",true,true,true,true,true,7,false,true,"One of Europe's most walkable and affordable capitals, with hilltop viewpoints, vintage trams, and incredible seafood. The nightlife runs late and the city buzzes with creative energy day and night.",["Walkable","Great food","Historic","Affordable","Nightlife"]),
d("Porto","Portugal",1,["culture","calm"],"offbeat",true,true,true,true,true,7,false,true,"Porto is Lisbon's smaller, grittier sibling — a UNESCO-listed city of azulejo tiles, port wine cellars, and stunning riverside views. Compact enough to explore on foot and far less crowded.",["Wine","UNESCO","Riverside","Compact","Charming"]),
d("Algarve","Portugal",1,["calm","culture"],"famous",true,true,true,true,true,7,false,false,"Portugal's golden southern coast offers dramatic sea cliffs, hidden grottos, and some of Europe's finest beaches. Beyond the sand, whitewashed fishing villages and outstanding seafood.",["Beaches","Cliffs","Seafood","Sunshine","Relaxed"]),
d("Sintra","Portugal",1,["culture","calm"],"offbeat",true,false,true,true,true,7,false,false,"Sintra is a fairy-tale town of Romantic palaces and castles rising from forested hills just 30 minutes from Lisbon. A UNESCO World Heritage Site that feels genuinely magical.",["Palaces","UNESCO","Fairy-tale","Romantic","Scenic"]),
d("Alentejo","Portugal",1,["calm"],"hidden",true,false,true,true,true,7,false,false,"Portugal's vast interior plateau of rolling cork forests, medieval walled villages, and some of the country's finest wines. Almost no tourists and a pace of life that feels like another century.",["Wine","Rural","Peaceful","Medieval","Authentic"]),
d("Barcelona","Spain",1,["culture","nightlife"],"famous",true,true,true,true,false,8,false,true,"Europe's ultimate city for culture and nightlife — Gaudí's architecture astounds by day while clubs don't get going until 2am. Built for groups who want to split up and reunite over long late dinners.",["Nightlife","Beach","Architecture","Food","Groups"]),
d("Madrid","Spain",1,["culture","nightlife"],"famous",true,true,true,true,true,8,false,true,"Spain's capital has the Prado, the Reina Sofía, and the Thyssen — three of the world's greatest art museums — plus a tapas culture and nightlife that runs until dawn.",["Art museums","Tapas","Nightlife","Royal","Vibrant"]),
d("Seville","Spain",1,["culture","nightlife"],"famous",true,true,true,true,true,8,false,false,"Seville is Andalusia at its most dramatic — flamenco, grand cathedrals, orange-tree-lined plazas, and a tapas culture that keeps restaurants buzzing until midnight.",["Flamenco","History","Tapas","Romantic","Architecture"]),
d("San Sebastián","Spain",1,["culture","calm"],"offbeat",true,true,true,true,true,8,false,false,"San Sebastián has more Michelin stars per capita than almost anywhere on earth. Nestled between mountains and a perfect crescent beach, it's one of Europe's most beautiful small cities.",["Foodie paradise","Beach","Michelin stars","Scenic","Relaxed"]),
d("Granada","Spain",1,["culture","calm"],"offbeat",true,true,true,true,true,8,false,false,"Granada is home to the Alhambra, one of the world's great palaces. Tapas are still free with every drink here, and the Moorish old quarter is one of Spain's most magical neighborhoods.",["Alhambra","Free tapas","Moorish","History","Affordable"]),
d("Valencia","Spain",1,["culture","nightlife"],"offbeat",true,true,true,true,true,8,false,false,"Valencia invented paella, has a futuristic arts complex by Calatrava, beautiful beaches, and a nightlife scene that's far more authentic than Barcelona's. Spain's most underrated major city.",["Paella","Beaches","Architecture","Authentic","Affordable"]),
d("Bilbao","Spain",1,["culture"],"offbeat",true,true,true,true,true,8,false,false,"The Guggenheim Bilbao transformed this industrial port city into a must-visit destination. The pintxos bars of the Casco Viejo rival anything in San Sebastián, and the city has a proud Basque character.",["Guggenheim","Pintxos","Basque","Art","Regeneration"]),
d("Ibiza","Spain",1,["nightlife","calm"],"famous",true,true,false,false,false,9,false,false,"Ibiza is the world's most famous party island with legendary clubs and world-class DJs. Beyond the clubs, the old walled town is a UNESCO site with great restaurants and a relaxed daytime vibe.",["Clubbing","Beach","DJ culture","Summer","Legendary"]),
d("Mallorca","Spain",1,["calm","culture"],"offbeat",true,false,true,true,true,9,false,false,"Beyond the package-holiday resorts, Mallorca hides a stunning mountainous interior, hidden coves, and beautiful stone villages. Rewards travelers willing to rent a car and explore.",["Hidden coves","Mountains","Beaches","Scenic","Diverse"]),
d("Tenerife","Spain",1,["calm","nightlife"],"offbeat",true,true,true,true,true,9,false,false,"Tenerife has Europe's highest peak, dramatic volcanic landscapes, eternal spring weather, whale watching, and both a resort-heavy south coast and a quiet, authentic north. Spain's most underrated island.",["Volcano","Whale watching","Spring weather","Beaches","Diverse"]),
// EUROPE - ITALY
d("Rome","Italy",1,["culture","nightlife"],"famous",true,true,true,true,true,9,false,true,"Rome is an open-air museum where you can eat the world's best cacio e pepe fifty meters from a 2,000-year-old monument. Every neighborhood has its own character, perfect for groups.",["History","Food","Art","Walking","Iconic"]),
d("Florence","Italy",1,["culture","calm"],"famous",true,true,true,true,true,9,false,true,"Florence is the world's greatest concentration of Renaissance art in a compact, walkable city — the Uffizi, Michelangelo's David, and Brunelleschi's dome, all within walking distance.",["Art","Renaissance","Walkable","Food","Wine"]),
d("Venice","Italy",1,["culture","calm"],"famous",true,false,true,true,false,9,false,true,"Venice is genuinely like nowhere else on earth — a city built on water where getting lost in the maze of canals is the whole point. Go in shoulder season to avoid the worst crowds.",["Unique","Canals","Romantic","Art","Architecture"]),
d("Milan","Italy",1,["culture","nightlife"],"famous",true,true,true,false,false,9,false,true,"Milan is Italy's fashion and design capital — the Duomo, the Last Supper, aperitivo culture, and some of Europe's best shopping. The nightlife in Navigli is among Italy's most sophisticated.",["Fashion","Design","Aperitivo","Shopping","Sophisticated"]),
d("Naples","Italy",1,["culture","nightlife"],"offbeat",true,true,true,true,false,9,false,false,"Chaotic, passionate, and utterly authentic — Naples is the birthplace of pizza and one of Italy's most vibrant cities. Pompeii and Herculaneum are just 30 minutes away.",["Pizza","Pompeii","Authentic","Vibrant","Food"]),
d("Amalfi Coast","Italy",1,["calm","culture"],"famous",false,false,true,true,false,9,false,false,"Cliffside villages tumbling into a turquoise sea, fresh pasta, and limoncello at sunset — the definitive romantic Italian escape. Hire a boat, eat too much, do nothing.",["Romantic","Coastal","Scenic","Italian food","Slow travel"]),
d("Sicily","Italy",1,["culture","calm"],"offbeat",true,true,true,true,true,10,false,false,"Sicily is Italy turned up to eleven — more ancient Greek ruins, more dramatic coastline, more extraordinary food, and half the tourists of the mainland.",["Ancient ruins","Food","Beaches","Authentic","Underrated"]),
d("Bologna","Italy",1,["culture","nightlife"],"offbeat",true,true,true,false,false,9,false,false,"Italy's most underrated city is also its greatest food city — birthplace of ragù, mortadella, and tortellini, with a lively university town energy and almost no tourist crowds.",["Food capital","University town","Authentic","Local","Underrated"]),
d("Tuscany","Italy",1,["calm","culture"],"famous",true,true,true,true,true,9,false,false,"Rolling hills, cypress-lined roads, hilltop medieval towns, Chianti wine, and a quality of light that has inspired artists for centuries. Tuscany is the Italy of everyone's imagination.",["Wine","Rolling hills","Medieval towns","Romantic","Iconic"]),
d("Puglia","Italy",1,["calm","culture"],"offbeat",true,true,true,true,true,10,false,false,"Italy's heel — trulli houses, olive groves, crystal-clear Adriatic coves, and some of Italy's best food and wine at half the price of Tuscany. The Italian countryside at its most authentic.",["Trulli","Olive groves","Adriatic","Authentic","Affordable"]),
d("Sardinia","Italy",1,["calm"],"offbeat",true,true,true,true,true,10,false,false,"Sardinia has some of the Mediterranean's most spectacular beaches — water so clear it rivals the Caribbean — plus a proud, distinct culture and cuisine entirely its own.",["Beaches","Clear water","Mediterranean","Authentic","Stunning"]),
d("Cinque Terre","Italy",1,["calm","culture"],"famous",true,false,true,false,false,9,false,false,"Five colorful fishing villages clinging to dramatic cliffs above the Ligurian Sea, connected by coastal hiking trails. Best in May or September when the crowds thin.",["Scenic","Hiking","Coastal","Colorful","Villages"]),
d("Turin","Italy",1,["culture","nightlife"],"hidden",true,true,true,true,true,9,false,false,"Turin is Italy's great overlooked city — baroque palaces, the Egyptian Museum, the birthplace of espresso and the aperitivo, and a sophistication that puts many better-known Italian cities to shame.",["Baroque","Espresso","Egyptian Museum","Sophisticated","Underrated"]),
// EUROPE - FRANCE
d("Paris","France",2,["culture","nightlife"],"famous",true,true,true,true,true,7,false,true,"Paris needs no introduction — the Louvre, the Eiffel Tower, the best bakeries on earth, and a café culture that makes simply sitting and watching the world go by a legitimate activity.",["Iconic","Art","Food","Romance","Fashion"]),
d("Lyon","France",2,["culture","nightlife"],"offbeat",true,true,true,true,true,8,false,false,"Lyon is France's gastronomic capital — the city of Paul Bocuse and bouchons, where even the most casual lunch is an event. The old town is a UNESCO site with a lively, unpretentious energy.",["Food capital","UNESCO","Bouchons","Authentic","Underrated"]),
d("Bordeaux","France",2,["culture","calm"],"offbeat",true,true,true,true,true,8,false,false,"Bordeaux is one of France's most beautiful cities — elegant 18th-century architecture, the world's greatest wine region on its doorstep, and a riverside esplanade that rivals Paris.",["Wine","Elegant","Riverside","Food","Beautiful"]),
d("Nice","France",2,["culture","calm","nightlife"],"famous",true,true,true,true,true,9,false,false,"Nice sits on the Côte d'Azur between the Alps and the Mediterranean — a vibrant city with a beautiful old town, the legendary Promenade des Anglais, and easy access to Monaco and Cannes.",["Riviera","Beach","Old town","Sunny","Gateway"]),
d("Strasbourg","France",2,["culture","calm"],"offbeat",true,true,true,true,true,8,false,false,"Strasbourg is a fairy-tale city on the Rhine — half French, half Alsatian, with half-timbered houses, a stunning Gothic cathedral, and Europe's finest Christmas market.",["Half-timbered","Gothic cathedral","Christmas market","Alsatian","Charming"]),
d("Provence","France",2,["calm","culture"],"famous",true,false,true,true,true,9,false,false,"Lavender fields, Roman ruins, hilltop villages, rosé wine, and an unhurried way of life — Provence is the France of postcards made real.",["Lavender","Roman ruins","Villages","Rosé","Picturesque"]),
d("Marseille","France",2,["culture","nightlife"],"offbeat",true,true,true,false,false,9,false,false,"France's second city is raw, multicultural, and genuinely exciting — a port city with an extraordinary fish market, some of France's best street art, and legendary bouillabaisse.",["Multicultural","Port","Street art","Bouillabaisse","Authentic"]),
d("Corsica","France",2,["calm","culture"],"offbeat",true,true,true,true,false,9,false,false,"Corsica is a mountain in the sea — dramatic granite peaks, maquis-scented air, some of France's most spectacular beaches, and a fiercely independent culture. The most beautiful island in the Mediterranean.",["Beaches","Mountains","Maquis","Dramatic","Beautiful"]),
// EUROPE - GERMANY & AUSTRIA
d("Berlin","Germany",1,["culture","nightlife"],"famous",true,true,true,true,false,8,false,true,"Berlin has the world's best club scene, outstanding museums, extraordinary street art, and a creative energy unlike any other European capital. Dinner at midnight, clubs until Tuesday.",["Clubbing","Museums","Street art","Creative","Nightlife"]),
d("Munich","Germany",1,["culture","nightlife"],"famous",true,true,true,true,true,9,false,true,"Munich combines world-class museums, stunning baroque architecture, a thriving beer garden culture, and easy access to the Bavarian Alps. Oktoberfest is the obvious draw, but the city shines year-round.",["Beer gardens","Bavaria","Museums","Alps nearby","Oktoberfest"]),
d("Hamburg","Germany",1,["culture","nightlife"],"offbeat",true,true,true,true,false,8,false,false,"Hamburg is Germany's most underrated city — a port metropolis with the legendary Reeperbahn, a stunning harbour, the new Elbphilharmonie, and some of Germany's best food.",["Port","Nightlife","Music","Elbphilharmonie","Underrated"]),
d("Vienna","Austria",1,["culture","nightlife"],"famous",true,true,true,true,true,9,false,true,"Vienna is Europe's grandest imperial city — extraordinary museums, coffee house culture, opera, and some of the world's finest pastry.",["Imperial","Coffee culture","Museums","Opera","Elegant"]),
d("Salzburg","Austria",1,["culture","calm"],"offbeat",true,false,true,true,true,9,false,false,"Mozart's birthplace sits at the foot of the Alps in a picture-perfect Baroque city. A UNESCO-listed old town, mountain cable cars, and the most scenic surroundings of any city in Central Europe.",["Baroque","Alps","Mozart","UNESCO","Scenic"]),
d("Innsbruck","Austria",1,["calm","culture"],"offbeat",true,true,true,true,false,9,false,false,"Innsbruck sits in a dramatic Alpine bowl — world-class skiing in winter, mountain biking and hiking in summer, and a charming medieval old town all year.",["Alps","Skiing","Hiking","Medieval","Dramatic views"])
);

fs.writeFileSync('/home/claude/max-dinamyte-travel/dest_part1.json', JSON.stringify(destinations));
console.log('Part 1:', destinations.length, 'destinations');
