const fs = require('fs');
const d = (name,country,al,vibes,fam,solo,groups,couples,fam2,young,fh,drive,direct,desc,tags,extras) => {
  const obj = {name,country,advisoryLevel:al,vibes,familiarity:fam,goodForSolo:solo,goodForGroups:groups,goodForCouples:couples,goodForFamilies:fam2,goodForYoungKids:young,flightHours:fh,driveFromUS:drive,directFlight:direct,description:desc,tags};
  if(extras) Object.assign(obj,extras);
  return obj;
};
const destinations = [];
// UK & IRELAND
destinations.push(
d("London","United Kingdom",1,["culture","nightlife"],"famous",true,true,true,true,true,7,false,true,"London is one of the world's great cities — free world-class museums, extraordinary theatre, a dining scene that rivals Paris, and neighbourhoods so distinct they each feel like separate cities.",["Free museums","Theatre","Diverse","Neighbourhoods","Iconic"]),
d("Edinburgh","United Kingdom",1,["culture","nightlife"],"famous",true,true,true,true,true,7,false,true,"Edinburgh is one of the world's great capital cities — a dramatic castle on a volcanic rock, a medieval Old Town, a Georgian New Town, and some of the world's best whisky bars.",["Castle","Whisky","History","Fringe festival","Dramatic"]),
d("Glasgow","United Kingdom",1,["culture","nightlife"],"offbeat",true,true,true,true,false,7,false,false,"Glasgow is Scotland's most vibrant city — a brilliant music scene, world-class art galleries, outstanding food, and a warmth of character that makes it one of Europe's most welcoming cities.",["Music","Art galleries","Friendly","Food","Authentic"]),
d("Scottish Highlands","United Kingdom",1,["calm"],"offbeat",true,true,true,true,false,8,false,false,"The Scottish Highlands offer some of Europe's most dramatic and unspoiled landscapes — lochs, glens, ancient castles, and a solitude that's increasingly hard to find anywhere on the continent.",["Lochs","Castles","Dramatic","Wild","Road trip"]),
d("Dublin","Ireland",1,["culture","nightlife"],"famous",true,true,true,true,false,7,false,true,"Dublin's pub culture is the stuff of legend — live traditional music, extraordinary conversation, and a warmth that makes strangers feel like old friends within minutes. Compact, walkable, and endlessly entertaining.",["Pubs","Live music","Craic","Walkable","Friendly"]),
d("Galway","Ireland",1,["culture","calm"],"offbeat",true,true,true,true,true,7,false,false,"Ireland's most characterful city is a gateway to the wild Atlantic Way — a bohemian, music-filled town with a brilliant food scene and the dramatic Connemara landscape on its doorstep.",["Music","Bohemian","Atlantic","Food","Authentic"]),
d("Ring of Kerry","Ireland",1,["calm"],"famous",true,true,true,true,true,8,false,false,"One of Europe's most scenic drives — 179km of Atlantic coastline, mountains, lakes, and ancient ruins through County Kerry. Spectacular at any time of year.",["Scenic drive","Atlantic","Mountains","Ancient ruins","Stunning"]),
// SCANDINAVIA
d("Copenhagen","Denmark",1,["culture","nightlife"],"famous",true,true,true,true,true,8,false,true,"Copenhagen consistently ranks among the world's most liveable cities. The food scene is extraordinary, the design culture is inspiring, and the waterfront Nyhavn district is one of Europe's most photogenic.",["Design","Food scene","Waterfront","Cycling","Hygge"]),
d("Reykjavik","Iceland",1,["culture","calm"],"offbeat",true,true,true,true,false,5,false,true,"Iceland's tiny capital is the gateway to some of the world's most dramatic landscapes — northern lights, geysers, waterfalls, and black sand beaches all within a few hours' drive.",["Northern lights","Nature","Geysers","Unique","Adventure"]),
d("Stockholm","Sweden",1,["culture","nightlife"],"famous",true,true,true,true,true,8,false,true,"Stockholm is spread across 14 islands — a strikingly beautiful capital with outstanding museums, a vibrant food scene, and Gamla Stan, one of Europe's best-preserved medieval old towns.",["Islands","Beautiful","Museums","Medieval","Scandinavian"]),
d("Oslo","Norway",1,["culture","calm"],"offbeat",true,true,true,true,true,8,false,false,"Oslo is compact, clean, and quietly extraordinary — the Viking Ship Museum, the Munch Museum, and the stunning Oslofjord. The gateway to Norway's fjords.",["Fjords","Viking history","Clean","Outdoors","Museums"]),
d("Bergen","Norway",1,["culture","calm"],"offbeat",true,true,true,true,true,8,false,false,"Bergen is the gateway to Norway's UNESCO-listed fjords — a charming harbor city of painted wooden houses, fish markets, and cable car rides to mountain viewpoints.",["Fjords","Harbor","Wooden houses","UNESCO","Scenic"]),
d("Helsinki","Finland",1,["culture","calm"],"offbeat",true,true,true,true,true,9,false,false,"Helsinki is a design-forward, sea-facing capital with a distinctive Nordic-Russian character, outstanding food, genuine sauna culture, and island archipelagos just minutes from the city.",["Design","Sauna","Archipelago","Nordic","Unique"]),
d("Faroe Islands","Denmark",1,["calm"],"hidden",true,true,true,false,false,8,false,false,"The Faroe Islands are 18 volcanic islands in the North Atlantic — dramatic sea cliffs, turf-roofed villages, and landscapes of such raw beauty they look almost computer-generated.",["Dramatic","Remote","Turf roofs","Cliffs","Untouched"]),
d("Lofoten Islands","Norway",1,["calm"],"hidden",true,true,true,false,false,9,false,false,"Dramatic peaks rising from the Arctic Ocean, red fishing cabins on stilts, northern lights in winter, and midnight sun in summer — the Lofoten Islands are among the most spectacular places in Europe.",["Arctic","Northern lights","Dramatic","Fishing villages","Midnight sun"]),
// BENELUX & SWITZERLAND
d("Amsterdam","Netherlands",1,["culture","nightlife"],"famous",true,true,true,true,false,8,false,true,"Amsterdam's canal-ringed streets, world-class museums, and legendary café culture make it one of Europe's most liveable cities. Endlessly explorable by bike.",["Canals","Museums","Cycling","Nightlife","Culture"]),
d("Bruges","Belgium",1,["culture","calm"],"offbeat",true,false,true,true,true,8,false,false,"Bruges is a medieval masterpiece — canals, Gothic architecture, chocolate shops, and a pace of life that feels centuries removed from the modern world.",["Medieval","Canals","Chocolate","Beer","Romantic"]),
d("Brussels","Belgium",2,["culture","nightlife"],"offbeat",true,true,true,true,true,8,false,false,"Brussels is more than its EU reputation — Art Nouveau architecture, extraordinary waffles and frites, some of the world's best beer, and the magnificent Grand Place.",["Grand Place","Beer","Waffles","Art Nouveau","Underrated"]),
d("Ghent","Belgium",1,["culture","nightlife"],"hidden",true,true,true,true,true,8,false,false,"Ghent is Belgium's most overlooked city — a spectacular medieval center with three towers, one of Europe's greatest paintings, and a thriving craft beer and restaurant scene.",["Medieval","Beer","Authentic","Art","Hidden gem"]),
d("Zurich","Switzerland",1,["culture","calm"],"offbeat",true,false,true,true,true,9,false,true,"Switzerland's largest city sits on a lake with Alps on the horizon — extraordinarily beautiful, impeccably clean, and a gateway to world-class skiing and hiking.",["Lake","Alps","Clean","Safe","Stunning"]),
d("Geneva","Switzerland",1,["culture","calm"],"offbeat",true,false,true,true,true,9,false,false,"Geneva sits at the tip of Lake Geneva beneath the Alps — the world's most international city has extraordinary watchmaking heritage, world-class restaurants, and easy access to both Swiss and French Alps.",["International","Lake","Watchmaking","Alps","Refined"]),
d("Interlaken","Switzerland",1,["calm"],"offbeat",true,true,true,true,false,9,false,false,"Nestled between two lakes with the Jungfrau massif towering above, Interlaken is the adventure sports capital of the Alps — paragliding, skydiving, and world-class skiing.",["Adventure","Alps","Paragliding","Skiing","Stunning"]),
d("Lucerne","Switzerland",1,["calm","culture"],"offbeat",true,false,true,true,true,9,false,false,"Lucerne's medieval covered bridges, lake setting, and mountain backdrop make it one of Central Europe's most scenic towns.",["Scenic","Lake","Mountains","Medieval","Peaceful"]),
// EASTERN EUROPE
d("Prague","Czech Republic",1,["culture","nightlife"],"famous",true,true,true,true,true,9,false,false,"Prague's fairy-tale old town is one of Europe's best-preserved historic city centers. Far more affordable than Western Europe with outstanding food, beer, and culture.",["Historic","Affordable","Beautiful","Beer culture","Walkable"]),
d("Budapest","Hungary",1,["culture","nightlife"],"famous",true,true,true,true,false,9,false,false,"Budapest is one of Europe's most dramatic capitals — stunning architecture split across the Danube, legendary thermal baths, ruin bars, and a nightlife scene that rivals Berlin.",["Thermal baths","Ruin bars","Danube","Architecture","Nightlife"]),
d("Krakow","Poland",1,["culture","nightlife"],"offbeat",true,true,true,true,true,9,false,false,"Krakow's remarkably intact medieval old town is a UNESCO World Heritage Site, and the city has a vibrant bar and restaurant scene. One of Europe's most affordable great cities.",["UNESCO","Medieval","Affordable","Nightlife","History"]),
d("Warsaw","Poland",1,["culture","nightlife"],"hidden",true,true,true,true,true,9,false,false,"Warsaw has reinvented itself as one of Europe's most dynamic cities — a meticulously rebuilt old town, a booming food and cocktail scene, and an extraordinary story of resilience.",["Resilience","Rebuilt","Dynamic","Food scene","Underrated"]),
d("Ljubljana","Slovenia",1,["culture","calm"],"hidden",true,true,true,true,true,9,false,false,"Slovenia's tiny capital is one of Europe's best-kept secrets — a car-free old town, a hilltop castle, and the stunning Lake Bled just 45 minutes away.",["Hidden gem","Car-free","Castle","Lake Bled nearby","Peaceful"]),
d("Lake Bled","Slovenia",1,["calm"],"offbeat",true,false,true,true,true,9,false,false,"A glacial lake with a fairy-tale island church and a clifftop castle — Lake Bled looks almost too beautiful to be real. Perfect as an overnight stay.",["Fairy-tale","Lake","Castle","Scenic","Peaceful"]),
d("Tallinn","Estonia",1,["culture","nightlife"],"offbeat",true,true,true,true,true,9,false,false,"Tallinn's medieval old town is one of the best-preserved in Europe — cobblestone streets, ancient towers, and ramparts surrounding a beautifully walkable city center.",["Medieval","Affordable","Walkable","Charming","UNESCO"]),
d("Riga","Latvia",1,["culture","nightlife"],"hidden",true,true,true,true,true,9,false,false,"Riga has the largest collection of Art Nouveau architecture in the world, a beautiful medieval old town, and a surprisingly vibrant nightlife and food scene.",["Art Nouveau","Medieval","Baltic","Affordable","Underrated"]),
d("Vilnius","Lithuania",1,["culture","calm"],"hidden",true,true,true,true,true,9,false,false,"Vilnius has one of Eastern Europe's finest baroque old towns — a UNESCO site that feels authentically untouristed, with great coffee shops and a thriving arts scene.",["Baroque","UNESCO","Authentic","Arts","Undiscovered"])
);
fs.writeFileSync('/home/claude/max-dinamyte-travel/dest_part2.json', JSON.stringify(destinations));
console.log('Part 2:', destinations.length, 'destinations');
